@server = https://signol04-fictional-umbrella-56pwjx4r4w7f4qrw-8080.preview.app.github.dev
@emp = {{server}}/api/employees
###
GET {{emp}}
###
POST {{emp}}
Content-Type: application/json

{
    "firstName": "Quena",
    "lastName": "Viento",
    "description": "Tubo con huequitos"
}